### ISSUE TITLE
Weights for linear aligners demonstrated in the paper

### ISSUE THREAD

**Issue by vishaal27** [k1rezaei/Text-to-concept#1]
Thanks for the great work. I recognise that aligning representations from different visual models to CLIP's image encoder is fairly straightforward given your code. However, if you could release the weights of the linear layers that you trained for aligning the different visual models in Figure 5 that would be greatly appreciated! :)

**Comment by k1rezaei** [comment]
Thanks for your interest. Sure, I will upload some of those linear layers somewhere soon.

**Comment by k1rezaei** [comment]
Some of the pretrained aligners are uploaded.

**Comment by k1rezaei** [comment]
Some of the pretrained aligners are uploaded.
