### ISSUE TITLE
Alignment of two models with different source datasets.

### ISSUE THREAD

**Issue by Fay-why** [k1rezaei/Text-to-concept#3]
Dear author, 
Thanks for your novel work. 

I have observed that your work is capable of aligning the feature spaces of two models through a simple linear transformation. In the paper, I noticed that you tested different models with various architectures and training process. I am curious to know if the training domains (training dataset) of these models are consistent. If the training domains, including the feature space and category space, are inconsistent between the two models, can the feature spaces still be aligned through linear transformation?

**Comment by k1rezaei** [comment]
Hello, thanks for your positive feedback.

No, actually it is not necessary that these models are trained on the same dataset. In fact, even in our paper, CLIP models are trained on datasets with image-caption pairs (MS-COCO, LAION, ...) and vision encoders are trained on other datasets (ImageNet, ...).
To **train linear alignment**, we use same dataset for all models and learn the transformation matrices and vectors.

**Comment by Fay-why** [comment]
Thanks for your reply! I still wonder if the linear alignment works in small, different data region, because imagenet and laion are quite big datasets. 
I will close this issue.
